version: '3'
services:
  streaming-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sukhilnair/streaming:frontend_v0.1
    container_name: streaming-frontend
    environment:
      AWS_IP: "0.0.0.0"
      STREAM_PORT: 3002
    ports:
      - "9099:3000"

  auth-backend:
    build:
      context: ./backend/authService
      dockerfile: Dockerfile
    image: sukhilnair/streaming:backend_auth_v0.1
    container_name: authentication-backend
    environment:
      MONGO_URI: "mongodb+srv://sukhilnair:<password>@cluster0.dm4xp4t.mongodb.net/travelmemory"
      PORT: 3001
      JWT_SECRET: "writesomerandomsecrets"
      AWS_KEY_ID: 'asfdasdfasfasf'
      AWS_SECRET_KEY: 'adsafsasfdafs'
      AWS_REGION: 'ap-south-1'
      AWS_S3_BUCKET: 'streamingappservice'
    ports:
      - "3001:3001"

  stream-backend:
    build:
      context: ./backend/streamingService
      dockerfile: Dockerfile
    image: sukhilnair/streaming:backend_stream_v0.1
    container_name: stream-backend
    environment:
      MONGO_URI: "mongodb+srv://sukhilnair:<password>@cluster0.dm4xp4t.mongodb.net/travelmemory"
      PORT: 3002
      JWT_SECRET: "writesomerandomsecrets"
      AWS_KEY_ID: 'asfdasdfasfasf'
      AWS_SECRET_KEY: 'adsafsasfdafs'
      AWS_REGION: 'ap-south-1'
      AWS_S3_BUCKET: 'streamingappservice'
    ports:
      - "3002:3002"